# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877727f8cbdb832558f28bc42325cc87cfd5cb5451b3bc3bc44a00ab91785b0630426007cc48b8f62aa1960df854aba08a07bb38fab28e149ed75de676681903

test:
  secret_key_base: 6a7feefe6c233496bb77a263ddfc69ec6ed5d4ca2952426afb2dbd58c0d964a64a20c577591cb46ee774472e19a51d2f9280968151e9162696e28a8f11a7d1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
